---
-  name: Cluster1
   hostname: "127.0.0.1:9092"
   protocol: SASL_SSL    #Only supported option for now
   mechanism: PLAIN      #Only supported option for now
   jaasConfig: "org.apache.kafka.common.security.plain.PlainLoginModule   required username='xxxxxxxxxxxxx' password='xxxxxxxxxx';"

-  name: Cluster2
   hostname: "192.168.12.68:9092"
   protocol: SASL_SSL    #Only supported option for now
   mechanism: PLAIN      #Only supported option for now
   jaasConfig: "org.apache.kafka.common.security.plain.PlainLoginModule required username='xxxxxxxxxxxxx' password='xxxxxxxxxx';"